### ISSUE TITLE
Update information for "Down To Business". Details should be provided in May, not June

### ISSUE THREAD

**Issue by kalimar** [rubyforgood/rubyforgood.org--old#115]
Projects in 2017 will be focused on women’s issues and families. We have some great projects lined up but we need more! We need YOU to help us find other great projects - suggest a project below! Project details, including available teams to join, will be announced to attendees around the beginning of *June*. Team leads will get information on projects at the end of March.

**Comment by seanmarcia** [comment]
Great catch!

**Comment by seanmarcia** [comment]
Changed!
