### ISSUE TITLE
The last sentence here may no longer apply

### ISSUE THREAD

**Issue by kalimar** [rubyforgood/rubyforgood.org--old#117]
What to Bring
Bring yourself, your laptop, a power source, some clothes and your favorite board games. Maybe some sunscreen if the weather’s nice. If you anticipate skipping group meals, bring some munchies. If you’re a light sleeper, bring earplugs. All the basics are provided (linens, pillows, beds, towels, etc.). We have a fun outdoor activity planned for one evening so camping chairs, a sweater and maybe some bug spray are highly recommended.

**Comment by kalimar** [comment]
Also needs to be updated in the FAQ.

**Comment by craig-riecke** [comment]
This looks like it's been integrated, so closing.  If this is a mistake, please reopen!
