### ISSUE TITLE
Make these URLs in the FAQ into links

### ISSUE THREAD

**Issue by kalimar** [rubyforgood/rubyforgood.org--old#118]
What’s it REALLY like at Ruby for Good?

So glad you asked! For expert insight, here are a couple of blog posts written up by past attendees:

http://alwaysbelearning.co/2014/08/05/ruby-for-good/
http://www.blrice.net/blog/2014/08/09/lessons-learned-at-ruby-for-good/
http://rolentle.com/ruby-for-good/

**Comment by craig-riecke** [comment]
Reviewed - 'tis all done.
