### ISSUE TITLE
Open Issues Page

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/rubyforgood.org--old#122]
We should write a ruby script using octokit that looks through all the R4G repos and examines open issues for tags like Help Wanted as well as anything else that denotes issues that need help. Then add them to an open issues page.
This will help people who are remote and looking for projects to contribute to.
Something like this: 
https://codefordc.org/projects/
https://codefordc.org/projects/helpwanted.html
Thomas, one of our attendees built this: http://i-want-to-contribute.netlify.com/

He's happy to work with people to build a customized version for R4G

**Comment by craig-riecke** [comment]
I'm gonna split this into three Github issues:

- This one
- Issue #133 for Project Dashboard
- Issue #134 for Project Search

**Comment by craig-riecke** [comment]
Implemented by #139.

**Comment by csexton** [comment]
🎉
