### ISSUE TITLE
Dockerizing this app

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/rubyforgood.org--old#156]
Dockerizing this app with a Dockerfile and docker-compose.yml file provides a common development environment for everyone.  This would head off the infamous "but it works on my machine" problem.

**Comment by jhsu802701** [comment]
The solution is in Pull Request #159 .

**Comment by armahillo** [comment]
@jhsu802701  You realize this is a jekyll repo that deploys to GH pages, right?

Why should this be dockerized? 

I think it's great you're contributing to open source, but drive-by PRs where you aren't considering the contextual value-add really isn't helpful, and it just creates more work for the maintainers, who often (and definitely in this case) are volunteers. 

Docker isn't a panacea. There are *definitely* reasons to use it, but there is also maintenance overhead created by adding it, and from the looks of all the repos you're attempting to dockerize, I don't think you're considering those costs. There is a bit of hubris in assuming that you know how to "fix" a problem that hasn't been identified as such, in a project that you've never worked with before. Decisions about architecture, technology, etc are executive decisions and require a greater breadth and depth of knowledge about the problem domain and application.

If you want to get your Hacktoberfest credits, or just want to contribute to open source in general, have some humility and approach the project through the issues tab. Look at the problems that are actually trying to be solved. Our Ruby for Good projects are typically pretty good about using "Good First Issue" labels to indicate issues that are good for people new to the project, when that work is available. 

Have some humility and don't assume you know what's best for a project without building rapport with the code and the team first.

**Comment by jhsu802701** [comment]
I'm keeping the dockerization in my own special branch.

However, this app is broken if you git clone it now without getting the old Gemfile.lock file (which is not in the current source code).  I've provided a solution in Pull Request #161 .
