### ISSUE TITLE
Precise Location & Parking Info

### ISSUE THREAD

**Issue by bengm** [rubyforgood/rubyforgood.org--old#27]
The /location page driving directions direct attendees to the campus, but not necessarily the specific parking lot. Do we park at the Rappahannock parking deck (#42 on the map)? If I can get that info from someone, I'd happily submit a pull request for the page.
![image](https://cloud.githubusercontent.com/assets/819222/8960902/38dbcb6e-35e0-11e5-9ba3-1a63531b62de.png)

**Comment by teresafinn** [comment]
Yes, parking is available on the Rappahannock parking deck (across from our dorms) in the general area on levels 1 and 2, not the pre-pay section! Note there is no free parking on Thursday. :)
