### ISSUE TITLE
Create scholarship application form

### ISSUE THREAD

**Issue by csexton** [rubyforgood/rubyforgood.org--old#3]
@cupakromer and @asheren need to help!

**Comment by asheren** [comment]
1. finished this (on a branch) but it says failed authentication when I try to push. 
2. I need the arlington ruby for good google docs so I can share the spreadsheet so we can all have access when people apply.
3. Newbie question: How do I see the what the site looks like (cause I can't run the rails server to see it...)

**Comment by csexton** [comment]
1. This should be fixed, I added you as a collaborator.
2. Yeah, me too. @SeanMarcia?
3. It's just a static site, try double clicking on `index.html`*

\* Sometimes static sites don't work by opening the local file in a browser, with include paths and javascript requests—in that case you can make a simple web server by running this in the root directory of repo:

```
ruby -run -e httpd . -p 3000
```

**Comment by cupakromer** [comment]
@csexton that sounds like it's itching for your add a PR with a `README_DEV.md` and a helper script :stuck_out_tongue_winking_eye:
