### ISSUE TITLE
Move to `.org` domain

### ISSUE THREAD

**Issue by csexton** [rubyforgood/rubyforgood.org--old#30]
We own it, just need to move over to it. Seems like a good time to knock that out.
- [x] Update DNS to point to Github's IP for the `rubyforgood.org` apex record.
- [x] Update the `CNAME`
- [x] Rename this repo to match
- [x] Email addresses

**Comment by seanmarcia** [comment]
- [x] Rename this repo to match

**Comment by seanmarcia** [comment]
- [x] Redirected rubyforgood.com to rubyforgood.org

**Comment by csexton** [comment]
Nice use of checkboxen.

**Comment by csexton** [comment]
Crazy man @seanmarcia fixed the CNAME in https://github.com/rubyforgood/rubyforgood.org/commit/f745b704648521af9cc3c256a7efaf2a20e3b261

**Comment by seanmarcia** [comment]
Done.
