### ISSUE TITLE
Make communication gooder.

### ISSUE THREAD

**Issue by adunkman** [rubyforgood/rubyforgood.org--old#50]
Hey folks! We’re working on this for our Ruby for Good project (so meta). 

What could be improved about the current site (and other communication channels)? If you’ve gone in the past (or currently), what did you struggle with?

**Comment by adunkman** [comment]
It sounds like we have a consensus that there are a few different categories of things: 

Before the being committed to going or sponsoring: what is it, what kind of projects are done, what kind of impact does it have?

Once you’re committed to going or sponsoring: how do I buy tickets, do I have to sign up for anything additional ahead of time, when am I expected to be there so I can plan travel arrangements?

When you’re going: what do I pack, what address should I put into my maps, where do I go once I arrive on site? What’s the schedule during the event, when is lunch?

**Comment by juliancheal** [comment]
👍

**Comment by adunkman** [comment]
This seems to be pretty well taken care of — going to tidy up and close this!
