### ISSUE TITLE
Project Yearbook

### ISSUE THREAD

**Issue by csexton** [rubyforgood/rubyforgood.org--old#61]
The yearbooks will be one big page full of project, with details on the projects, the team leads and the owners. 
- [x] HTML-comment template at the top of the page and instructions on how to add pull request. 
- [x] Add instructions on how to open a pull request to add a project in the README
- [x] Add jekyll include for `twitter_user`
- Sections for the years:
  - [x] 2014
  - [x] 2015
  - [x] 2016

**Comment by adunkman** [comment]
![image](https://cloud.githubusercontent.com/assets/14930/16171450/3665196e-353d-11e6-9426-8008071d0d51.jpeg)

**Comment by kalimar** [comment]
testing integration
![gif-keyboard-18124402737526287618](https://cloud.githubusercontent.com/assets/1248672/16171488/1bfe4a36-353e-11e6-874e-3cab70e33d34.gif)

**Comment by adunkman** [comment]
I think this is donezo — reopen if you disagree! 

![giphy](https://cloud.githubusercontent.com/assets/14930/16177570/c01e6594-35ff-11e6-8eae-d889fd5d740f.gif)

**Comment by csexton** [comment]
👍
