### ISSUE TITLE
Faq page

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/rubyforgood.org--old#95]
What happened to it?

**Comment by CraigJZ** [comment]
Looks like we removed it at some point.  Added it back, so the content is available for future reference.  Right now it's not accessible from the nav.

**Comment by adunkman** [comment]
Is there some content you're looking for?

**Comment by seanmarcia** [comment]
Most of the content seems to be on the new attend page but it seems to be missing the whimsy :)
